name: saitamanga_core
version: 0.0.1
author: InNoobWeTrust <InNoobWeTrust@gmail.com>
description: Core library for SAITAMAnga project, a cross-platform & performance focused manga-reader.

environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'

executables:
  manga: main

dependencies:
  html: any
  yaml: any
  json_annotation: ^1.0.0

dev_dependencies:
  build_runner: any
  json_serializable: ^1.0.0
  test: any
  resource: any
