enum Id {
  category,
  category__title,
  category__cover,
  category__description,
  album,
  album__title,
  album__cover,
  album__description,
  collage,
  collage__title,
  collage__cover,
  collage__desscription,
  collage__picture,
  pagination,
  prev,
  next,
}
